### ISSUE TITLE
change volume color from white to other color

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#124]
![img_0270](https://cloud.githubusercontent.com/assets/19282172/17276435/0494f676-5747-11e6-8479-ef4d642ce35c.jpg)
How to change the default volume and video playing color from white to other color.
i am using ooyala default player  for ios.

**Comment by Matthew-C** [comment]
Hi Santhosh,

This is the classical UI. Color customization is not supported. Would you
consider using the v4 OoyalaSkin UI?

Thanks
Matthew

**Comment by santhoshrajs** [comment]
@Matthew-C 

I have integrated ooyala player v4 skin,but i cannot able to change the color of slider for volume and video.

![img_0271](https://cloud.githubusercontent.com/assets/19282172/17312901/60ca7776-5874-11e6-88fc-be31e16278b8.jpg)

From this image i need to change volume and video slider from blue color to red color.i have changed scrubberBar rgb color fromskin.json but didn't reflect it inapp.

Please help me asap to resolve this issue.

**Comment by Matthew-C** [comment]
these can be modified via skin.json, search for "control bar" and "scrubberBar" under that.

**Comment by santhoshrajs** [comment]
From skin.json under control bar we have these options
"controlBar": {
    "volumeControl": {
      "color": "#FFFFFF"
    },
    "iconStyle": {
      "active": {
        "color": "#FFFFFF",
        "opacity": 1.0
      },
      "inactive": {
        "color": "#FFFFFF",
        "opacity": 0.95
      }
    },
    "autoHide": true,
    "height": 60,
    "logo": {
      "imageResource": {"url": "//player.ooyala.com/static/v4/candidate/latest/skin-plugin/assets/images/ooyala-logo.svg","androidResource" : "logo","iosResource" : "logo"},
      "clickUrl": "http://www.ooyala.com",
      "target": "_blank",
      "width": 96,
      "height": 24
    },
    "adScrubberBar": {
      "backgroundColor": "rgba(175,175,175,1)",
      "bufferedColor": "rgba(127,127,127,1)",
      "playedColor": "rgba(255,63,128,1)"
    },
    "scrubberBar": {
      "backgroundColor": "rgba(175,175,175,0.5)",
      "bufferedColor": "rgba(175,175,175,0.7)",
      "playedColor": "rgba(67,137,255,1)",
      "thumbnailPreview": true
    }
  },

i have changed volume control color as well as scrubber bar color but color didn't reflect in app

**Comment by santhoshrajs** [comment]
@Matthew-C 

Any updates?
Still i am facing issue to change volume and video slider.
From this json structure i have changed volumeControl": {
"color": "#FFFFFF"
},
the above color to red but it didn't reflect in the app.
Kindly help me to resolve this issue.

**Comment by brol1dev** [comment]
Hi @santhoshrajs, I'm sorry we haven't commented on this ticket in a long time.

Currently in iOS, if you're using the new player v4 UI, you can change the volume thumb/indicator only. Right now, we don't support changing the slider bar color, it defaults to what Apple gives us. 

Also, we're missing documentation about this particular feature, so I'm including it here for you.
First, our volume thumb can only be customized with an image. We have a default one, which I don't think you're using by looking at the screen you provide, here're the Assets we provide with the native-skin: https://github.com/ooyala/native-skin/tree/stable/OoyalaSkinSDK.xcassets. Include it in your Xcode project and you'll see a VolumeThumb asset (https://github.com/ooyala/native-skin/tree/stable/OoyalaSkinSDK.xcassets/VolumeThumb.imageset).

To use the one we provide, go to the `Info.plist` of your app and add the following entry to the plist dictonary:
![screen shot 2016-11-17 at 3 33 20 pm 1](https://cloud.githubusercontent.com/assets/263478/20412406/5230a6b6-acdb-11e6-842c-89d5a9460390.png)

The `VolumeThumbImage` key is the important part, since is how we retrieve the name of the image in the code. The value is the name you gave to the asset, which for our sample apps we default to `VolumeThumb`, but you can decide to name it whatever you want here, just make sure it's the same name you used in your `.xcassets` file.

Here's a screenshot of our `OoyalaSkinSDK.xcassets` in our sample app.
![screen shot 2016-11-17 at 3 39 45 pm](https://cloud.githubusercontent.com/assets/263478/20412520/1f933614-acdc-11e6-887d-af25824f9314.png)

I recommend you using a 32x32 png image for the 2x image, and decide to add a 1x (16x16) or 3x (48x48) if you want to target devices more specifically.

That's all you need to change the volume thumb. Please let us know if you are able to change it.

Sorry again for the late response,
Eric
