### ISSUE TITLE
SDK 4.47.0_RC5

### ISSUE THREAD

**Issue by IgnSergey** [ooyala/ios-sample-apps#418]
Hello. 

When I was tried to test SDK 4.47.0_RC5, I discovered that in function 
`func token(forEmbedCodes embedCodes: [String], callback: @escaping OOEmbedTokenCallback)`
you totally block main thread until callback. That's why UI is not available, some mechanism for receiving data also blocked because uses main thread and we can have deadlock. 
Is this an issue or normal behavior?
Thanks.

**Comment by oSulyma** [comment]
Hello @IgnSergey 
I verified logic related to using `OOEmbedTokenGenerator` and found that private class that calls method `-tokenForEmbedCodes:callback:` first switches to global_queue and then calls  `-tokenForEmbedCodes:callback:`. Our cases of this protocol implementation in our sample apps work fine.

I could get deadlock only when I intentionally switched to main_queue before performing callback inside implementation of `-tokenForEmbedCodes:callback:` (in class that confirms `OOEmbedTokenGenerator`).
Could you attach snippet with your implementation of `-tokenForEmbedCodes:callback:`, please?

**Comment by IgnSergey** [comment]
Hello. Sorry for delay. For example:
func token(forEmbedCodes embedCodes: [String], callback: @escaping OOEmbedTokenCallback) {
    additionalAssetInfo()
        .then(on: defaultQueue) { (info) -> Void in
            callback(info?.token)
        }
        .always {
             callback(nil)
        }
}
additionalAssetInfo - difficult request maker and in some places uses main thread. 
What will be if backend has long time response? Until we receive data to call callback(...) UI will be blocked?
btw, version 4.46.0_GA works without this problem.

**Comment by IgnSergey** [comment]
we have class `OoyalaSecureHelper: NSObject, OOEmbedTokenGenerator, OOSecureURLGenerator { }` on init we connect all managers.
in player we have next code:
create instance of helper 
`ooyalaSecureHelper = OoyalaSecureHelper(...)`
`let options = OOOptions()`
use it
`options?.secureURLGenerator = ooyalaSecureHelper`
`player = OOOoyalaPlayer.createOnlinePlayer(forKey: embedCode, config: config, playerId: playerId, options: options, generator: ooyalaSecureHelper)`

**Comment by oSulyma** [comment]
@IgnSergey 
Thank you for additional info, it was helpful.
1 - It's strange, because I can get deadlock even with 4.46.0_GA. Just to remind: for this purpose I intentionally switch to main_queue in implementation of `-tokenForEmbedCodes:callback:` . Without switching to switch to **main_queue** - everything is ok.

2 - My investigation shows than the root of problem is:
SDK's class that uses `id <OOEmbedTokenGenerator>` designed to ask for token and wait for callback in **global queue** (dispatch_get_global_queue). 
Switching to **main queue** causes deadlock. It's occurs because in this time **main queue** is blocked by this SDK's class for another internal purpose. So when you try to switch to **main queue** it is already used.
I'm afraid we can't easily rewrite this class without danger to create new issues.  
Please, avoid performing `-tokenForEmbedCodes:callback:` in **main queue** if it's possible.

**Comment by IgnSergey** [comment]
What will be if backend has long time or no response? Until we receive data to call callback(...) UI will be blocked? Timeout in our app 30s -> for 30s UI will be blocked?

**Comment by oSulyma** [comment]
Agree, I missed this. I need more time for investigation how to solve this problem safely.

**Comment by DmitriiMaslov** [comment]
@IgnSergey  We fixed the issue and it will be released in 4.47.0 (the relased date initially was scheduled as of 20th of August but it can be moved to the later date for may be a week).

**Comment by maxkupetskii** [comment]
Since we released 4.47 with the fix I'm closing this issue.
